/**
 * @file app.config.ts
 * @description Per-game visual identity. Generated by tools/propagate-theme.js.
 * Edit the source script and re-run to update.
 */
export const APP_CONFIG = {
  name: "Tarot",
  primary: "#A855F7",
  secondary: "#6B21A8",
  splash: {
    glow: "rgba(107,33,168,0.6)",
    sallyGlow: "rgba(168,85,247,0.8)",
    pillBorder: "rgba(168,85,247,0.5)",
    pillBg: "rgba(107,33,168,0.15)",
    pillText: "#F3E8FF",
    suit: "✦",
    suit2: "◆",
  },
  slides: {
    slide2: { tint: ["rgba(168,85,247,0.55)","rgba(107,33,168,0.7)","rgba(15,8,30,0.95)"], variant: "spread" },
    slide3: { tint: ["rgba(192,132,252,0.45)","rgba(76,29,149,0.85)","rgba(15,8,30,0.95)"], variant: "grid" },
    slide4: { tint: ["rgba(217,70,239,0.45)","rgba(168,85,247,0.7)","rgba(15,8,30,0.95)"], variant: "scattered" },
  },
} as const;

export type SlideVariant = 'fan' | 'scattered' | 'spread' | 'grid';
